# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='depth',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.IntegerField(),
        ),
    ]
